[package]
name = "pastecli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.9"
serde_json = "1.0.79"
tokio = { version = "1.17.0", features=["full"] }
